/-
Copyright (c) 2026 LieTheory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LieTheory contributors
-/
import LieTheory.Sl2Classification.Basic

/-!
# Highest-weight vectors and the `sl₂` string

This file packages the primitive-vector results from `Mathlib.Algebra.Lie.Sl2`
with a natural-number highest weight.
-/

namespace LieTheory.Sl2Classification

open LieModule

universe u v w

variable {K : Type u} {L : Type v} {M : Type w}
variable [Field K] [LieRing L] [LieAlgebra K L]
variable [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L} (t : IsSl2Triple h e f)

/-- A primitive vector whose `h`-weight has been identified with a natural
number. -/
structure HighestWeightVector where
  weight : ℕ
  vector : M
  isPrimitive : t.HasPrimitiveVectorWith vector (weight : K)

namespace HighestWeightVector

variable {t}

/-- Every nonzero finite-dimensional representation over an algebraically
closed field of characteristic zero has a highest-weight vector of natural
weight. -/
theorem exists_highestWeightVector [CharZero K] [IsAlgClosed K] [Nontrivial M]
    [FiniteDimensional K M] :
    Nonempty (HighestWeightVector (K := K) (M := M) t) := by
  obtain ⟨μ, m, -, P⟩ := t.exists_hasPrimitiveVectorWith (R := K) (M := M)
  obtain ⟨n, hn⟩ := P.exists_nat
  exact ⟨⟨n, m, hn ▸ P⟩⟩

/-- The `i`th vector in the string generated by repeatedly applying `f`. -/
def stringVector (P : HighestWeightVector (K := K) (M := M) t) (i : ℕ) : M :=
  ((toEnd K L M f) ^ i) P.vector

@[simp]
theorem stringVector_zero (P : HighestWeightVector (K := K) (M := M) t) :
    P.stringVector 0 = P.vector := by
  simp [stringVector]

/-- Applying `f` advances one place along the highest-weight string. -/
theorem lie_f_stringVector (P : HighestWeightVector (K := K) (M := M) t) (i : ℕ) :
    ⁅f, P.stringVector i⁆ = P.stringVector (i + 1) := by
  exact P.isPrimitive.lie_f_pow_toEnd_f i

/-- Every string vector is an `h`-eigenvector of the expected weight. -/
theorem lie_h_stringVector (P : HighestWeightVector (K := K) (M := M) t) (i : ℕ) :
    ⁅h, P.stringVector i⁆ = ((P.weight : K) - 2 * (i : K)) • P.stringVector i := by
  exact P.isPrimitive.lie_h_pow_toEnd_f i

/-- Applying `e` to the successor string vector moves back one place with the
standard coefficient. -/
theorem lie_e_stringVector_succ
    (P : HighestWeightVector (K := K) (M := M) t) (i : ℕ) :
    ⁅e, P.stringVector (i + 1)⁆ =
      (((i : K) + 1) * ((P.weight : K) - i)) • P.stringVector i := by
  exact P.isPrimitive.lie_e_pow_succ_toEnd_f i

/-- The string vectors through index `weight` are nonzero. -/
theorem stringVector_ne_zero (P : HighestWeightVector (K := K) (M := M) t)
    [CharZero K] {i : ℕ} (hi : i ≤ P.weight) : P.stringVector i ≠ 0 := by
  exact P.isPrimitive.pow_toEnd_f_ne_zero_of_eq_nat rfl hi

/-- The highest-weight string terminates immediately after index `weight`. -/
theorem stringVector_succ_weight_eq_zero
    [CharZero K] [FiniteDimensional K M]
    (P : HighestWeightVector (K := K) (M := M) t) :
    P.stringVector (P.weight + 1) = 0 := by
  exact P.isPrimitive.pow_toEnd_f_eq_zero_of_eq_nat rfl

end HighestWeightVector

end LieTheory.Sl2Classification
